dist: trusty

language: c

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc make build-essential linux-headers-$(uname -r)
  - mkdir -p src/mcu/bin
  - wget -c 'http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/plain/mt7601u.bin' -O 'src/mcu/bin/MT7601.bin'

install: true

script:
  - make clean
  - make all
  - sudo insmod src/os/linux/mtutil7601Usta.ko
  - sudo insmod src/os/linux/mt7601Usta.ko
  - sudo insmod src/os/linux/mtnet7601Usta.ko
  - sudo rmmod mtnet7601Usta
  - sudo rmmod mt7601Usta
  - sudo rmmod mtutil7601Usta
