language: c

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc make build-essential linux-headers-$(uname -r)

install: true

script:
  - make clean
  - make all
